[package]
name = "simple-ica-host"
version = "0.3.0"
authors = ["Ethan Frey <ethanfrey@users.noreply.github.com>"]
edition = "2021"
publish = false
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# for quicker tests, cargo test --lib

[dependencies]
simple-ica = { path = "../../packages/simple-ica" }

cosmwasm-std = { path = "../../../cosmwasm/packages/std", features = ["iterator", "stargate"] }
cw-storage-plus = { path = "../../../cw-storage-plus" }
cw-utils = { path = "../../../cw-minus/packages/cw-utils" }
schemars       = { version = "0.8.22" }
serde          = { version = "1.0.103", features = ["derive"], default-features = false }
thiserror      = { version = "1.0.23" }

cw1-whitelist = { path = "../../../cw-plus/contracts/cw1-whitelist" }

[dev-dependencies]
cosmwasm-schema = { path = "../../../cosmwasm/packages/schema" }

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true
